"""add stock reservations

Revision ID: 1bdc987f2eac
Revises: 88f6c668c456
Create Date: 2026-10-01 13:58:37.524297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bdc987f2eac'
down_revision: Union[str, Sequence[str], None] = '88f6c668c456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_reservations',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('variant_id', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('status', sa.Enum('active', 'consumed', 'released',
                                                'expired', name='stock_reservation_status'), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('expires_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.CheckConstraint(
                        'quantity > 0', name='ck_stock_reservations_quantity_positive'),
                    sa.ForeignKeyConstraint(
                        ['variant_id'], ['product_variants.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_stock_reservations_id'),
                    'stock_reservations', ['id'], unique=False)
    op.create_index(op.f('ix_stock_reservations_variant_id'),
                    'stock_reservations', ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_reservations_variant_id'),
                  table_name='stock_reservations')
    op.drop_index(op.f('ix_stock_reservations_id'),
                  table_name='stock_reservations')
    op.drop_table('stock_reservations')
    sa.Enum(
        name="stock_reservation_status"
    ).drop(
        op.get_bind(),
        checkfirst=True
    )
    # ### end Alembic commands ###
