"""add orders and order items

Revision ID: 75e9fe70d5e3
Revises: fe2020b8b250
Create Date: 2026-10-08 16:55:10.653511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75e9fe70d5e3'
down_revision: Union[str, Sequence[str], None] = 'fe2020b8b250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('status', sa.Enum('pending', 'paid', 'cancelled',
                              'refunded', name='order_status'), nullable=False),
                    sa.Column('total_amount', sa.Numeric(
                        precision=10, scale=2), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('order_items',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('order_id', sa.Integer(), nullable=False),
                    sa.Column('variant_id', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('unit_price', sa.Numeric(
                        precision=10, scale=2), nullable=False),
                    sa.Column('line_total', sa.Numeric(
                        precision=10, scale=2), nullable=False),
                    sa.CheckConstraint(
                        'quantity > 0', name='ck_order_items_quantity_positive'),
                    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
                    sa.ForeignKeyConstraint(
                        ['variant_id'], ['product_variants.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_order_items_id'),
                    'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'),
                    'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_variant_id'),
                    'order_items', ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_variant_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    sa.Enum(
        name="order_status"
    ).drop(
        op.get_bind(),
        checkfirst=True
    )
    # ### end Alembic commands ###
