"""add cart and cart_item models

Revision ID: fe2020b8b250
Revises: 1bdc987f2eac
Create Date: 2026-10-02 15:34:57.886407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe2020b8b250'
down_revision: Union[str, Sequence[str], None] = '1bdc987f2eac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('status', sa.Enum('active', 'checked_out',
                              'abandoned', name='cart_status'), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_cart_id'), 'cart', ['id'], unique=False)
    op.create_table('cart_item',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('cart_id', sa.Integer(), nullable=False),
                    sa.Column('variant_id', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.CheckConstraint(
                        'quantity > 0', name='ck_cart_items_quantity_positive'),
                    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
                    sa.ForeignKeyConstraint(
                        ['variant_id'], ['product_variants.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_cart_item_cart_id'),
                    'cart_item', ['cart_id'], unique=False)
    op.create_index(op.f('ix_cart_item_id'), 'cart_item', ['id'], unique=False)
    op.create_index(op.f('ix_cart_item_variant_id'),
                    'cart_item', ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cart_item_variant_id'), table_name='cart_item')
    op.drop_index(op.f('ix_cart_item_id'), table_name='cart_item')
    op.drop_index(op.f('ix_cart_item_cart_id'), table_name='cart_item')
    op.drop_table('cart_item')
    op.drop_index(op.f('ix_cart_id'), table_name='cart')
    op.drop_table('cart')
    sa.Enum(
        name="cart_status"
    ).drop(
        op.get_bind(),
        checkfirst=True
    )
    # ### end Alembic commands ###
